[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@rari-capital/solmate/=lib/solmate/',
    '@uniswap/v2-core/=lib/v2-core/',
    '@uniswap/v2-periphery/=lib/v2-periphery/',
    'ERC721A/=lib/ERC721A/',
]
solc_version = "0.8.15"
gas_reports = ["*"]


# See more config options https://github.com/gakonst/foundry/tree/master/config
